### ISSUE TITLE
About the time complexity of attach_memory_bank.py

### ISSUE THREAD

**Issue by TinaChen95** [heatz123/naturalspeech#17]
Hi,

I'm trying to reproduce the results on ljspeech dataset, and I noticed that the code in this section (https://github.com/heatz123/naturalspeech/blob/ca2f814d960149a8fdc3f3e4d773abb67e7c18ec/attach_memory_bank.py#L132) takes a very long time to execute. It appears that the shape of X is (7066362, 192), which leads to a high computational complexity when calculating the distances.

I was wondering if you could share with me how much time it takes for this code to run on your machine?
Thanks

**Comment by Aliasgarsaifee** [comment]
Yeah got same issue, for me it had taken around around 10 hours on machine. It runs on CPU that's why it is more slower. And this time is for `n_init=1` which is running  _1 iteration_ equivalent to `n_init="auto"`.

**Comment by wen0320** [comment]
Hi,do you have follow question: 

12399 torch.Size([192, 651])
(7066362, 192)
Traceback (most recent call last):
  File "attach_memory_bank.py", line 174, in <module>
    centers = k_means(zs)
  File "attach_memory_bank.py", line 132, in k_means
    kmeans = KMeans(n_clusters=1000, random_state=0, n_init="auto").fit(X)
  File "/home/WeiWB/anaconda3/envs/tts/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1146, in fit
    self._check_params(X)
  File "/home/WeiWB/anaconda3/envs/tts/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 937, in _check_params
    if self.n_init <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
