### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by wen0320** [heatz123/naturalspeech#23]
Hi,When I tried to duplicate your code,in 7.initialize and attach memory bank after warmup:
  python3 attach_memory_bank.py -c configs/ljs.json --weights_path logs/[run_name]/G_xxx.pth.The following problems arise
12199 torch.Size([192, 660])
12299 torch.Size([192, 859])
12399 torch.Size([192, 651])
(7066362, 192)
Traceback (most recent call last):
  File "attach_memory_bank.py", line 174, in <module>
    centers = k_means(zs)
  File "attach_memory_bank.py", line 132, in k_means
    kmeans = KMeans(n_clusters=1000, random_state=0, n_init="auto").fit(X)
  File "/home/WeiWB/anaconda3/envs/tts/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1146, in fit
    self._check_params(X)
  File "/home/WeiWB/anaconda3/envs/tts/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 937, in _check_params
    if self.n_init <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by Aliasgarsaifee** [comment]
It is because of sklearn version issue. Use latest version >=1.24.0

**Comment by wen0320** [comment]
Thank you for your reply.Hello, the latest version of this package sklearn (scikit-learn 1.2.2) is 1.2.2, there is no version 1.24.0. And the highest version in the mirror source is 1.0.2.
