### ISSUE TITLE
Error While running Train.py

### ISSUE THREAD

**Issue by athenasaurav** [heatz123/naturalspeech#27]
Hello Everyone, I m getting this error when i m running `python train.py -c configs/ljs_reproduce.json -m ljs --warmup`
```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/NS/speech/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/NS/speech/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/NS/naturalspeech/utils/data_utils.py", line 514, in __call__
    duration_padded[i, : text. Size(0)] = duration
RuntimeError: The expanded size of the tensor (319) must match the existing size (321) at non-singleton dimension 0.  Target sizes: [319].  Tensor sizes: [321]
```
I have run the `preprocess_durations.py` and copied the duration folder from VITS folder to Naturalspeech folder. Could someone please tell me what the issue is?

Also to mention to run the `preprocess_durations.py` I had to downgrade my torch version to the VITS version. I am using the LJSpeech-Dataset directly downloaded from [here](https://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2)

**Comment by ghost** [comment]
I jumped through the same hoops. After downgrading your torch version to calculate the durations you'll have to update it back to a more recent version, e.g. `pip install torch==1.13.0` makes it go away, but brace yourself for more errors along the way. It's not exactly smooth sailing.

**Comment by AvichalJain** [comment]
Hi @remy-radix,
I am still facing the same issue even after updating it.
